###
GET http://localhost:3000

###
POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "todo": "NodeJS"
}

###
PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 4,
  "todo": "Ujang"
}

###
DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 2
}